name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate stats card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: ${{ github.repository_owner }}
          stats: true
          path: profile/stats.svg
          token: ${{ secrets.PAT_1 }}
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add profile/stats.svg
          git commit -m "chore: update stats" || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_1 }}`
          branch: ${{ github.ref }}
